import type { Listing } from "./types";

/**
 * Stats de marketplace calculados sobre los mocks. Cuando se conecte Supabase
 * se reemplaza por un SELECT count() + MAX(created_at) del server.
 */
export function getMarketplaceStats() {
  const active = MOCK_LISTINGS.filter((l) => l.status === "active");
  const now = Date.now();
  const oneDay = 24 * 60 * 60 * 1000;
  const newToday = active.filter(
    (l) => now - new Date(l.created_at).getTime() < oneDay,
  ).length;
  const latest = active.reduce<string | null>(
    (acc, l) => (!acc || l.created_at > acc ? l.created_at : acc),
    null,
  );
  const totalTonnage = active.reduce((sum, l) => sum + l.tonnage, 0);
  return {
    activeCount: active.length,
    newToday,
    latestAt: latest,
    totalTonnage,
  };
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    user_id: "u1",
    grain_type: "soja",
    tonnage: 500,
    country: "AR",
    region: "Córdoba",
    city: "Río Cuarto",
    price: 410,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-05-15",
    description:
      "Soja de primera, humedad 13,5%, grano sano. Entrega desde planta propia con balanza. Flete a cargo del comprador.",
    status: "active",
    image_url: null,
    created_at: "2026-04-18T12:00:00Z",
    updated_at: "2026-04-18T12:00:00Z",
    seller: {
      id: "u1",
      full_name: "Agro del Sur SRL",
      user_type: "seller",
      country: "AR",
      region: "Córdoba",
      city: "Río Cuarto",
    },
  },
  {
    id: "2",
    user_id: "u2",
    grain_type: "maiz",
    tonnage: 1200,
    country: "BR",
    region: "Mato Grosso",
    city: "Sorriso",
    price: null,
    currency: "USD",
    price_mode: "to_agree",
    delivery_date: "2026-06-01",
    description:
      "Maíz zafrinha, calidad exportación. Lotes disponibles mensualmente desde Rondonópolis y Sorriso. Condición FOB Paranaguá.",
    status: "active",
    image_url: null,
    created_at: "2026-04-20T09:30:00Z",
    updated_at: "2026-04-20T09:30:00Z",
    seller: {
      id: "u2",
      full_name: "Fazenda Esperança Ltda",
      user_type: "both",
      country: "BR",
      region: "Mato Grosso",
      city: "Sorriso",
    },
  },
  {
    id: "3",
    user_id: "u3",
    grain_type: "trigo",
    tonnage: 300,
    country: "UA",
    region: "Odesa",
    city: "Odesa",
    price: 240,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-04-30",
    description:
      "Trigo pan, proteína 11,5%, PH 78. Disponible en terminal portuaria. Carga inmediata.",
    status: "active",
    image_url: null,
    created_at: "2026-04-21T16:45:00Z",
    updated_at: "2026-04-21T16:45:00Z",
    seller: {
      id: "u3",
      full_name: "Black Sea Grain Co.",
      user_type: "seller",
      country: "UA",
      region: "Odesa",
      city: "Odesa",
    },
  },
  {
    id: "4",
    user_id: "u4",
    grain_type: "soja",
    tonnage: 2000,
    country: "US",
    region: "Iowa",
    city: "Des Moines",
    price: 405,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-05-25",
    description:
      "US No. 2 Yellow Soybeans. Available in container or bulk. Payment against BL. Origin certificates included.",
    status: "active",
    image_url: null,
    created_at: "2026-04-17T10:15:00Z",
    updated_at: "2026-04-17T10:15:00Z",
    seller: {
      id: "u4",
      full_name: "Midwest Grain Traders LLC",
      user_type: "seller",
      country: "US",
      region: "Iowa",
      city: "Des Moines",
    },
  },
  {
    id: "5",
    user_id: "u5",
    grain_type: "maiz",
    tonnage: 400,
    country: "AR",
    region: "Entre Ríos",
    city: "Paraná",
    price: 185,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-05-10",
    description:
      "Maíz temprano, humedad 14%. Entrega en planta o puerto Rosario. Consultar disponibilidad de camiones.",
    status: "active",
    image_url: null,
    created_at: "2026-04-19T08:20:00Z",
    updated_at: "2026-04-19T08:20:00Z",
    seller: {
      id: "u5",
      full_name: "Don Ernesto e Hijos",
      user_type: "seller",
      country: "AR",
      region: "Entre Ríos",
      city: "Paraná",
    },
  },
  {
    id: "6",
    user_id: "u6",
    grain_type: "trigo",
    tonnage: 150,
    country: "FR",
    region: "Île-de-France",
    city: "París",
    price: 220,
    currency: "EUR",
    price_mode: "to_agree",
    delivery_date: "2026-05-05",
    description:
      "Blé tendre panifiable, protéines 12%. Possibilité de contrats forward. Livraison Rouen.",
    status: "active",
    image_url: null,
    created_at: "2026-04-22T07:00:00Z",
    updated_at: "2026-04-22T07:00:00Z",
    seller: {
      id: "u6",
      full_name: "Céréales Île-de-France",
      user_type: "both",
      country: "FR",
      region: "Île-de-France",
      city: "París",
    },
  },
  {
    id: "7",
    user_id: "u7",
    grain_type: "girasol",
    tonnage: 250,
    country: "AR",
    region: "Buenos Aires",
    city: "Tres Arroyos",
    price: 520,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-06-10",
    description:
      "Girasol alto oleico, humedad 10%. Contrato forward disponible. Carga en terminal Quequén.",
    status: "active",
    image_url: null,
    created_at: "2026-04-22T15:00:00Z",
    updated_at: "2026-04-22T15:00:00Z",
    seller: {
      id: "u7",
      full_name: "Agroindustrial del Sur",
      user_type: "seller",
      country: "AR",
      region: "Buenos Aires",
      city: "Tres Arroyos",
    },
  },
  {
    id: "8",
    user_id: "u8",
    grain_type: "sorgo",
    tonnage: 800,
    country: "AR",
    region: "Santa Fe",
    city: "Rafaela",
    price: 175,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-05-20",
    description:
      "Sorgo granífero, apto forraje y exportación. Entrega puerto San Lorenzo. Cortado y acondicionado.",
    status: "active",
    image_url: null,
    created_at: "2026-04-16T11:00:00Z",
    updated_at: "2026-04-16T11:00:00Z",
    seller: {
      id: "u8",
      full_name: "Cooperativa Rafaela Ltda",
      user_type: "seller",
      country: "AR",
      region: "Santa Fe",
      city: "Rafaela",
    },
  },
  {
    id: "9",
    user_id: "u9",
    grain_type: "cebada",
    tonnage: 600,
    country: "AR",
    region: "Buenos Aires",
    city: "Tandil",
    price: 210,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-07-01",
    description:
      "Cebada cervecera variedad Andreia. Proteína 11,5%. Contrato con maltería regional disponible.",
    status: "active",
    image_url: null,
    created_at: "2026-04-21T09:00:00Z",
    updated_at: "2026-04-21T09:00:00Z",
    seller: {
      id: "u9",
      full_name: "Estancia La Providencia",
      user_type: "seller",
      country: "AR",
      region: "Buenos Aires",
      city: "Tandil",
    },
  },
  {
    id: "10",
    user_id: "u10",
    grain_type: "avena",
    tonnage: 120,
    country: "CA",
    region: "Saskatchewan",
    city: "Saskatoon",
    price: 380,
    currency: "USD",
    price_mode: "to_agree",
    delivery_date: "2026-06-15",
    description:
      "Oat milling grade. Test weight 40 lb/bu+. Certificates on request. CWB origin. Containerized.",
    status: "active",
    image_url: null,
    created_at: "2026-04-22T03:30:00Z",
    updated_at: "2026-04-22T03:30:00Z",
    seller: {
      id: "u10",
      full_name: "Prairie Grains Co-op",
      user_type: "seller",
      country: "CA",
      region: "Saskatchewan",
      city: "Saskatoon",
    },
  },
  {
    id: "11",
    user_id: "u11",
    grain_type: "arroz",
    tonnage: 400,
    country: "BR",
    region: "Rio Grande do Sul",
    city: "Pelotas",
    price: 590,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-05-30",
    description:
      "Arroz largo fino tipo 1, parboilizado disponible bajo pedido. Embalaje 25kg o bulk. Puerto Rio Grande.",
    status: "active",
    image_url: null,
    created_at: "2026-04-20T17:20:00Z",
    updated_at: "2026-04-20T17:20:00Z",
    seller: {
      id: "u11",
      full_name: "Arrozeira do Sul SA",
      user_type: "seller",
      country: "BR",
      region: "Rio Grande do Sul",
      city: "Pelotas",
    },
  },
  {
    id: "12",
    user_id: "u12",
    grain_type: "maiz",
    tonnage: 3500,
    country: "UA",
    region: "Mikolaiv",
    city: "Mikolaiv",
    price: 195,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-06-05",
    description:
      "Ukrainian yellow corn, GMO-free. Test weight 72 kg/hl. Phyto certificate included. FOB Mikolaiv.",
    status: "active",
    image_url: null,
    created_at: "2026-04-19T14:45:00Z",
    updated_at: "2026-04-19T14:45:00Z",
    seller: {
      id: "u12",
      full_name: "Dnipro Agritrade",
      user_type: "both",
      country: "UA",
      region: "Mikolaiv",
      city: "Mikolaiv",
    },
  },
  {
    id: "13",
    user_id: "u13",
    grain_type: "trigo",
    tonnage: 900,
    country: "AU",
    region: "Western Australia",
    city: "Perth",
    price: 260,
    currency: "USD",
    price_mode: "to_agree",
    delivery_date: "2026-07-10",
    description:
      "Australian Premium White (APW) wheat. Protein 10-11.5%. CBH Group certified. Bulk vessel loading.",
    status: "active",
    image_url: null,
    created_at: "2026-04-18T22:10:00Z",
    updated_at: "2026-04-18T22:10:00Z",
    seller: {
      id: "u13",
      full_name: "Westgrain Exports Pty",
      user_type: "seller",
      country: "AU",
      region: "Western Australia",
      city: "Perth",
    },
  },
  {
    id: "14",
    user_id: "u14",
    grain_type: "soja",
    tonnage: 1500,
    country: "PY",
    region: "Itapúa",
    city: "Encarnación",
    price: 398,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-05-18",
    description:
      "Soja zafra 2026. Humedad 13%. Carga puerto Villeta. Contratos forward para campaña siguiente.",
    status: "active",
    image_url: null,
    created_at: "2026-04-17T19:00:00Z",
    updated_at: "2026-04-17T19:00:00Z",
    seller: {
      id: "u14",
      full_name: "Agro Itapúa SA",
      user_type: "seller",
      country: "PY",
      region: "Itapúa",
      city: "Encarnación",
    },
  },
  {
    id: "15",
    user_id: "u15",
    grain_type: "girasol",
    tonnage: 450,
    country: "RU",
    region: "Rostov",
    city: "Rostov-on-Don",
    price: null,
    currency: "USD",
    price_mode: "to_agree",
    delivery_date: "2026-06-20",
    description:
      "Russian sunflower seed, confectionery grade. 98% purity. Shipment ex-Novorossiysk port.",
    status: "active",
    image_url: null,
    created_at: "2026-04-15T08:00:00Z",
    updated_at: "2026-04-15T08:00:00Z",
    seller: {
      id: "u15",
      full_name: "South Steppe Agro",
      user_type: "seller",
      country: "RU",
      region: "Rostov",
      city: "Rostov-on-Don",
    },
  },
  {
    id: "16",
    user_id: "u16",
    grain_type: "arroz",
    tonnage: 200,
    country: "IN",
    region: "Punjab",
    city: "Amritsar",
    price: 640,
    currency: "USD",
    price_mode: "fixed",
    delivery_date: "2026-05-28",
    description:
      "Basmati rice, long grain. 1121 variety. Export-grade packaging. Origin certificate available.",
    status: "active",
    image_url: null,
    created_at: "2026-04-14T13:30:00Z",
    updated_at: "2026-04-14T13:30:00Z",
    seller: {
      id: "u16",
      full_name: "Himalaya Exports Pvt",
      user_type: "seller",
      country: "IN",
      region: "Punjab",
      city: "Amritsar",
    },
  },
];
